const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const JSZip = require('jszip');
function load(relative, overrides = {}) {
  const filename = path.resolve(__dirname, '..', relative);
  const m = new Module(filename, module); m.filename = filename; m.paths = Module._nodeModulePaths(path.dirname(filename));
  const original = m.require.bind(m);
  m.require = id => overrides[id] || (id.startsWith('@/') ? load(`${id.slice(2)}.ts`, overrides) : id.startsWith('.') ? load(path.relative(path.resolve(__dirname, '..'), path.resolve(path.dirname(filename), `${id}.ts`)), overrides) : original(id));
  m._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {compilerOptions: {module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true}}).outputText, filename);
  return m.exports;
}
const {collectBackup,backupZIP,readBackup,validateBackup,restoreBackup}=load('lib/backup/cms.ts');
const image=Buffer.from([1,2,3,4]);
const asset={_id:'image-old-2x2-png',_type:'sanity.imageAsset',url:'https://cdn.sanity.io/images/test/production/a.png',originalFilename:'proof.png',mimeType:'image/png',size:4};
const docs=[{_id:'settings',_type:'siteSettings',_rev:'old',logo:{asset:{_ref:asset._id}}},{_id:'drafts.settings',_type:'siteSettings',defaultLanguage:'ti'},{_id:'private.entry.one',_type:'playerEntry',proofScreenshot:{asset:{_ref:asset._id}},other:{_ref:'settings'}}];
function source(items=[...docs,asset]){return {config:()=>({projectId:'test',dataset:'production'}),fetch:async(q,p,o)=>{assert.equal(o.perspective,'raw');return items.filter(d=>d._id>p.after).sort((a,b)=>a._id.localeCompare(b._id,'en',{sensitivity:'variant'})).slice(0,500);}};}
function destination(failAt=0){let calls=0;const saved=new Map();let uploads=0;return {saved,get uploads(){return uploads},getDocuments:async ids=>ids.map(id=>saved.get(id)||null),assets:{upload:async(type,blob)=>{uploads++;assert.equal(blob.size,4);saved.set('image-new-2x2-png',{_id:'image-new-2x2-png'});return {_id:'image-new-2x2-png'}}},transaction(){const ops=[];const tx={createIfNotExists(d){ops.push(['add',d]);return tx},createOrReplace(d){ops.push(['replace',d]);return tx},async commit(){calls++;if(calls===failAt)throw new Error('permission denied');for(const [kind,d] of ops){if(kind==='replace'||!saved.has(d._id))saved.set(d._id,d)}}};return tx}};}
async function bundle(){const snapshot=await collectBackup(source());const bytes=await backupZIP(snapshot,()=>{},async()=>new Response(image));return readBackup(bytes.buffer,true);}
test('full ZIP contains original media, drafts, private receipts and a valid manifest',async()=>{const prepared=await bundle();assert.equal(prepared.backup.documents.length,3);assert.equal(prepared.backup.assets.length,1);assert.deepEqual(Buffer.from(prepared.files.get(asset._id)),image);});
test('ZIP round trip uploads missing media, remaps nested references, preserves IDs and removes revision metadata',async()=>{const target=destination();target.saved.set('unrelated',{_id:'unrelated'});const count=await restoreBackup(target,await bundle());assert.equal(count,3);assert.equal(target.uploads,1);assert.equal(target.saved.get('settings').logo.asset._ref,'image-new-2x2-png');assert.equal(target.saved.get('settings')._rev,undefined);assert.ok(target.saved.has('drafts.settings'));assert.ok(target.saved.has('unrelated'));});
test('old JSON backups restore when referenced assets exist',async()=>{const parsed=await readBackup(Buffer.from(JSON.stringify({documents:docs})),false);const target=destination();target.saved.set(asset._id,asset);assert.equal(await restoreBackup(target,parsed),3);assert.equal(target.uploads,0);});
test('missing references fail before any content is written',async()=>{const target=destination();await assert.rejects(()=>restoreBackup(target,{backup:validateBackup({documents:docs}),files:new Map()}),/Missing referenced/);assert.equal(target.saved.size,0);});
test('malformed and duplicate documents and system IDs are rejected',()=>{for(const input of [{}, {documents:[{}]}, {documents:[docs[0],docs[0]]}, {documents:[{_id:'_.system',_type:'settings'}]}, {documents:docs,format:'unexpected'}])assert.throws(()=>validateBackup(input));});
test('failed or truncated media downloads never produce a complete ZIP',async()=>{const backup=await collectBackup(source());await assert.rejects(()=>backupZIP(backup,()=>{},async()=>new Response('no',{status:503})),/Could not download/);await assert.rejects(()=>backupZIP(backup,()=>{},async()=>new Response('x')),/Incomplete/);});
test('restore validates media integrity before writing',async()=>{const prepared=await bundle();prepared.files.set(asset._id,new Uint8Array([9,9,9,9]));const target=destination();await assert.rejects(()=>restoreBackup(target,prepared),/integrity/);assert.equal(target.saved.size,0);});
test('interrupted restore reports failure and can be retried',async()=>{const prepared=await bundle();const target=destination(2);await assert.rejects(()=>restoreBackup(target,prepared),/Restore stopped/);assert.equal(await restoreBackup(target,prepared),3);});
test('contact endpoint never reports success when storage is unavailable',async()=>{const request=()=>new Request('https://test/api/contact',{method:'POST',body:JSON.stringify({phone:'0911000000',message:'Please help'})});for(const client of [null,{create:async()=>{throw new Error('offline')}}]){const {POST}=load('app/api/contact/route.ts',{'@/lib/sanity/client':{getSanityWriteClient:()=>client}});assert.equal((await POST(request())).status,503);}});
test('contact endpoint validates input and saves private contact documents',async()=>{let saved;const {POST}=load('app/api/contact/route.ts',{'@/lib/sanity/client':{getSanityWriteClient:()=>({create:async d=>{saved=d}})}});const req=body=>new Request('https://test/api/contact',{method:'POST',body:JSON.stringify(body)});assert.equal((await POST(req({phone:42,message:'Hello'}))).status,400);assert.equal((await POST(req({phone:'0911000000',message:'Hello'}))).status,200);assert.match(saved._id,/^private.contact./);});
test('export paginates all documents beyond the first 500',async()=>{const items=Array.from({length:1005},(_,i)=>({_id:'entry'+String(i).padStart(5,'0'),_type:'playerEntry'}));assert.equal((await collectBackup(source(items))).documents.length,1005);});
test('broken ZIP files are rejected before restore',async()=>{const zip=new JSZip();zip.file('cms_data_snapshot.json',JSON.stringify((await bundle()).backup));const bytes=await zip.generateAsync({type:'uint8array'});await assert.rejects(()=>readBackup(bytes.buffer,true),/missing media/);});
test('community registration validates contact and saves idempotently to CMS',async()=>{const docs=new Map();const client={createIfNotExists:async d=>{if(!docs.has(d._id))docs.set(d._id,d)}};const {POST}=load('app/api/subscribe/route.ts',{'@/lib/sanity/client':{getSanityWriteClient:()=>client}});const req=contact=>new Request('https://test/api/subscribe',{method:'POST',body:JSON.stringify({contact})});assert.equal((await POST(req('not-valid'))).status,400);assert.equal((await POST(req('Example@example.com'))).status,200);assert.equal((await POST(req('example@example.com'))).status,200);assert.equal(docs.size,1);assert.equal([...docs.values()][0].status,'unread');});
